### ISSUE TITLE
Error handling .lyrx file 

### ISSUE THREAD

**Issue by VeronicaKoess** [arc2qgis/qlyrx#20]
By trying to using the plugin, I am getting this Python Error:

> WARNING    Traceback (most recent call last):
>         File "C:\Users/xy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1613, in run
>         self.apply_lyrx_symbols(layer, self.j_data, geometry_general_type_str)
>         File "C:\Users/xy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1335, in apply_lyrx_symbols
>         if renderers[0]['type'] != "CIMSimpleRenderer":
>        TypeError: string indices must be integers
             
This is the .lyrx file I am trying to open in qgis:
[GIS_Services_HJAGIS_Elevation_Surfaces_1.lyrx.txt](https://github.com/user-attachments/files/15839176/GIS_Services_HJAGIS_Elevation_Surfaces_1.lyrx.txt)
The whole folder (unzip e.g. with 7zip) can be downloaded here:
[HJ Andrews Experimental Forest (LTER)](https://www.arcgis.com/sharing/rest/content/items/9a5d011563604990b061f3a960073b77/data)

I am using the lates plugin Version [v0.3.3](https://github.com/arc2qgis/qlyrx/releases/download/v0.3.3/qlyrx.zip) QGIS Version 3.28.12 on  Windows10 (64 bit)

**Comment by bogind** [comment]
Hi,
While I don't have a layer for reference, I can see your *.lyrx files are meant to style raster (in this case image service) layers.  
Please note in the README that raster symbology is not yet supported and development will likely take a while.

The error messages you got are unrelated to this, but they have also been fixed in v0.3.5 which is now available.
